### ISSUE TITLE
Random.nextLong(long bound)

### ISSUE THREAD

**Issue by mehdi-reza** [piomin/sample-spring-kafka-microservices#1]
https://github.com/piomin/sample-spring-kafka-microservices/blob/4082c112988bdda02d880075f81100d457c68eae/order-service/src/main/java/pl/piomin/order/service/OrderGeneratorService.java#L29

There is no method nextLong available which takes an upper bound.

**Comment by tnusraddinov** [comment]
Java 17 has that method.

**Comment by piomin** [comment]
As @tnusraddinov mentioned I'm using Java 17. Install it, it the latest LTS :)

```
    <properties>
        <java.version>17</java.version>
    </properties>
```
