### ISSUE TITLE
payment-service returns wrong status if reserve fails

### ISSUE THREAD

**Issue by gergolep** [piomin/sample-spring-kafka-microservices#2]
https://github.com/piomin/sample-spring-kafka-microservices/blob/4082c112988bdda02d880075f81100d457c68eae/payment-service/src/main/java/pl/piomin/payment/service/OrderManageService.java#L32

As the documentation it should return "REJECT" instead of "REJECTED".  With "REJECTED" status at the streams join the Order status property will be evaluate to null and the listeners will got NullPointerExceptions.

**Comment by piomin** [comment]
Resolved. Thanks!
